//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazanNeft.DB.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPhoto
    {
        public long ID { get; set; }
        public long AssetID { get; set; }
        public byte[] AssetPhoto1 { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
